With asl3-update-nodelist, *IF* a differential change was downloaded but the patch could not be applied the .orig/.rej files were being left in the "/tmp" directory.  After enough updates the available storage could be filled and then the .service would start failing.
This change improves the error handling.

diff --git a/asl3-update-nodelist b/asl3-update-nodelist
--- a/asl3-update-nodelist
+++ b/asl3-update-nodelist
@@ -28,17 +28,31 @@ USERAGENT="asl3-update-nodelist/1.0"
 FILEPATH=/var/lib/asterisk
 EXTNODES=$FILEPATH/rpt_extnodes
 EXTNODESTMP=$(mktemp)
-HASH_FILE="${FILEPATH}/asl3un-hash"
+HASH_FILE=${FILEPATH}/asl3un-hash
 
 getLastHash() {
 	last_hash=$(head -n1 ${HASH_FILE})
 }
 
 writeHash() {
-	curr_hash=$(grep SHA1 $EXTNODESTMP | cut -d "=" -f 2 | tail -n 1)
+	curr_hash=$(grep SHA1 $EXTNODES | cut -d "=" -f 2 | tail -n 1)
 	echo "${curr_hash}" > $HASH_FILE
 }
 
+downloadNodelist() {
+	wget --user-agent="$USERAGENT" -q -O $EXTNODESTMP "${NODE_URL}${1}"
+	if [ $? -ne 0 ]; then
+		echo "failed to download from ${NODE_URL}"
+		rm -f $EXTNODESTMP
+		exit 1
+	fi
+}
+
+writeNodelist() {
+	# Does app_rpt need the file not to change?
+	cat ${1} > ${EXTNODES}
+	writeHash
+}
 
 # See if this is a full or differential
 [ ! -f $HASH_FILE ] && touch $HASH_FILE
@@ -46,19 +60,14 @@ QS=""
 getLastHash
 [ "${last_hash}" != '' ] && QS="?hash=${last_hash}"
 
-wget --user-agent="$USERAGENT" -q -O $EXTNODESTMP "${NODE_URL}${QS}"
-if [ $? -ne 0 ]; then
-	echo "failed to download from ${NODE_URL}"
-	exit 1
-fi
+# Download the Nodelist
+downloadNodelist "${QS}"
 
-RETVAL=0
 diff_type=$(head -n1 ${EXTNODESTMP} | sed -e 's/^;//g')
 case $diff_type in
 	Full)
 		# Does app_rpt need the file not to change?
-		cat ${EXTNODESTMP} > ${EXTNODES}
-		writeHash
+		writeNodelist ${EXTNODESTMP}
 	;;
 
 	Empty)
@@ -67,13 +76,15 @@ case $diff_type in
 	Diff)
 		NEW_FILE=$(mktemp)
 		cp ${EXTNODES} ${NEW_FILE}
-		patch -t -s ${NEW_FILE} ${EXTNODESTMP}
+		patch -t -s -r 1 ${NEW_FILE} ${EXTNODESTMP}
 		if [ $? -eq 0 ]; then
-			# Does app_rpt need the file not to change?
-			cat ${NEW_FILE} > ${EXTNODES}
-			writeHash
+			# if all hunks applied successfully
+			writeNodelist ${NEW_FILE}
 		else
-			REVAL=1
+			# if some hunks cannot be applied or there were merge conflicts
+			# or there is more serious trouble, download the "Full" Nodelist
+			downloadNodelist ""
+			writeNodelist ${EXTNODESTMP}
 		fi
 		rm $NEW_FILE
 	;;
@@ -86,4 +97,4 @@ if [ ${USER} != "asterisk" ]; then
 	chmod 644 ${EXTNODES} ${HASH_FILE}
 fi
 
-exit $RETVAL
+exit 0
