rewrite in bash

diff --git a/asl3-update-astdb b/asl3-update-astdb
--- a/asl3-update-astdb
+++ b/asl3-update-astdb
@@ -1,147 +1,91 @@
-#!/usr/bin/php -q
-<?php
+#!/usr/bin/bash
+#
+#
+# AllStarLink extnodes generator
+#
+# Copyright (C) 2018-2024, AllStarLink, Inc.
+#
+# Written by:
+# Jason McCormick, N8EI 
+#
+# Adapted from a PHP version of the same name by
+# Tim Sawyer WD6AWP
+# with updates from WA3DSP, KK9ROB, KB4FX, 
+# WA3WCO, and others.
+#
+# See http://allstarlink.org for more information about
+# this project. Please do not directly contact
+# any of the maintainers of this project for assistance;
+# the project provides a web site, and mailing lists
+# for your use.
+#
+# This program is free software, distributed under the terms of
+# the GNU General Public License Version 3. See the LICENSE file
+# at the top of the source tree.
 
-// Code refactored / debugged by KB4FXC, 11/06/2018.
-// Fixed issue where error conditions were always generated by private nodes.
+if [ ${UID} -ne 0 ]; then
+	echo "ERROR: must run as root"
+	exit 1
+fi
 
-// Updated to check for strictly private nodes
-// and change load order - private first
-// WA3DSP 2/2016
-// KK9ROB 4/2021
-// $Id $
+DB_HOST=allmondb.allstarlink.org
+DB_URL="http://${DB_HOST}/"
+USERAGENT="asl3-update-astdb/1.0"
 
-// Original code by WD6AWP
-// Modified to run immediately when called directly
-// and load randomly within  30 minute window when
-// called by cron
+PRIV_FILE="/etc/asterisk/privatenodes.txt"
+DB_FILE="/var/lib/asterisk/astdb.txt"
 
-// Refactor to use CURL --- KB4FXC 11/19/2018
-// Refactor to use ASL distro --- KK9ROB 04/19/2021
-
-/* Refactored 2020-02-29 WD6AWP
-   - Use file_get_contents for $url
-   - Comment HamVoIP url
-   - Add $dir for storage location
-   - Reformat indentation
-   - Minor edits to messages
- */
-
-/* ASL3 update 2024-06-21 WA3WCO
-   - Move DB storage to /var/lib/asterisk (/var/log/asterisk is "tmpfs")
-   - Add symlinks to keep "popular" add-ons happy
- */
-
-$dir = "/etc/asterisk/";
-$privatefile = $dir . "privatenodes.txt";
-
-$astdb = "astdb.txt";
-$db = "/var/lib/asterisk/" . $astdb;
-
-$retries = 0;
-$Acontents = '';	// AllStarLink nodes
-$Pcontents = '';	// Private nodes
-$private = getenv('PRIVATE_NODE');
-$contents = '';
-
-$url = "http://allmondb.allstarlink.org/";
-
-// Load private nodes if any
-// Private nodes are less than 2000 and loaded first
-// to ensure proper order of file
-if (file_exists($privatefile)) {
-    $Pcontents .= file_get_contents($privatefile);
+function cleanup_files(){
+	rm -f ${TMP_FILE} ${TMP_DL}
 }
 
-// Check if ONLY private nodes
-// In that case do not read Allstar database
-// Maintains compatibility with pre 1.3 versions
-// assumes empty environment variable
-if (is_null($private) || !$private) {  // If not a private node...
-    // If called by cron wait between 0 and 30 min
-    if (isset($argv[1]) && $argv[1] == 'cron') {
-        $seconds = mt_rand(0, 1800);
-        print "Waiting for $seconds seconds...\n";
-        while ($seconds > 0) {
-            if ($seconds > 60) {
-                print "Sleeping for $seconds seconds...\n";
-                sleep(60);
-                $seconds = $seconds - 60;
-            } else {
-                print "Sleeping for $seconds seconds...\n";
-                sleep($seconds);
-                $seconds = 0;
-            }
-        }
-    }
+# Store WIP here
+TMP_FILE=$(mktemp)
 
-    while (true) {
-        // Open AllStar db URL and retrieve file.
-        $Acontents = @file_get_contents($url);
+# If there's a private file, process that
+if [ -f ${PRIV_FILE} ]; then
+	cat ${PRIV_FILE} >> ${TMP_FILE}
+fi
 
-        // Test size.
-        $size = strlen($Acontents);
-        if ($size < 300000) {
-            if ($retries >= 5) {
-                die ("astdb.txt: Retries exceeded!!  $size bytes - Invalid: file too small, bailing out.\n");
-            }
+# If the variable PRIAVE_NODE is set, stop here
+if [ ! -z "${PRIVATE_NODE}" ]; then
+	exit 0
+fi
 
-            $retries++;
-            print "Retry $retries of 5. Will retry $url\n";
-            sleep(5);
-        } else {
-            break;
-        }
-    }
-} // End private node check
+# Get the file from ASL
+TMP_DL=$(mktemp)
+wget -q -t 5 --user-agent="$USERAGENT" -O ${TMP_DL} "${DB_URL}"
+RETVAL=$?
 
-$contents =  $Pcontents;
-$contents .= $Acontents;
+# If wget failed, stop
+if [ ${RETVAL} -ne 0 ]; then
+	echo "ERROR: failed to download db file from ${DB_URL}"
+	cleanup_files
+	exit 1
+fi
 
-// Added to strip non printing characters.
-$contents = preg_replace('/[\x00-\x09\x0B-\x0C\x0E-\x1F\x7F-\xFF]/', '', $contents);
+# If the file is likely junk, stop
+DB_LINES=$(wc -l ${TMP_DL} | awk '{print $1}') 
+if [ ${DB_LINES} -lt 25 ]; then
+	echo "ERROR: file < 25 lines; likely garbage"
+	cleanup_files
+	exit 1
+fi
 
-// Save the data
-if (!($fh = fopen($db, 'w'))) {
-    die("Cannot open $db.");
-}
-if (!flock($fh, LOCK_EX)) {
-    echo 'Unable to obtain lock.';
-    exit(-1);
-}
-if (fwrite($fh, $contents) === false) {
-    die ("Cannot write $db.");
-}
-fclose($fh);
+# Combine and process
+cat ${TMP_DL} >> ${TMP_FILE}
+perl -pi -e 's/[\x00-\x09\x0B-\x0C\x0E-\x1F\x7F-\xFF]//g' ${TMP_FILE}
 
-// Update ownership
-if ((posix_geteuid() == 0) && (fileowner($db) == 0)) {
-    if (!chown($db, 'asterisk') || !chgrp($db, 'asterisk')) {
-	print "$db: could not set filesystem permissions\n";
-    }
-}
+# Install in all the places
+mv ${TMP_FILE} ${DB_FILE}
+chown -R asterisk:asterisk ${DB_FILE}
+for DIR in /var/log/asterisk /var/www/html/supermon /var/www/html/allscan; do
+	if [ -d ${DIR} ]; then
+		rm -f ${DIR}/astdb.txt
+		ln -s ${DB_FILE} ${DIR}/astdb.txt
+	fi
+done
 
-// Add symlinks to keep "popular" add-ons happy
-$addons = ["/var/log/asterisk", "/var/www/html/supermon", "/var/www/html/allscan"];
-foreach ($addons as $d) {
-    if (is_dir($d)) {
-	// if add-on [directory] exists
-	$l = $d . "/" . $astdb;
-	if (is_file($l) && !is_link($l)) {
-	    // if "astdb.txt" exists in the add-on directory AS A FILE
-	    print "Removing $l\n";
-	    unlink($l);
-	}
-	if (! file_exists($l)) {
-	    // add symlink to our "astdb.txt"
-	    if (symlink($db, $l)) {
-		print "Added symlink ($db <-- $l)\n";
-	    } else {
-		print "Could not create symlink ($db <-- $l)\n";
-	    }
-	}
-    }
-}
-
-$size = strlen($contents);
-print "Success: astdb.txt $size bytes\n";
-?>
+cleanup_files
+echo "Updated ${DB_FILE} with new database of ${DB_LINES} lines"
+exit 0
